# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='_board',
            new_name='board',
        ),
    ]
