# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170521_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='o_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='x_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
