# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170521_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.BooleanField(default=True),
        ),
    ]
