# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_game_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.NullBooleanField(),
        ),
    ]
