# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.CharField(default='[[null, null, null], [null, null, null], [null, null, null]]', max_length=255),
        ),
    ]
